$axure.loadCurrentPage({
  "url":"clubb.html",
  "generationDate":new Date(1416701658550.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d52d55abda424ee5b0325b73135462e7",
    "type":"Axure:Page",
    "name":"ClubB",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"13e1bc62a5864bc9bf2a10d73a7118f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":197,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"808b515d389b4e1a8ba14be16174d556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":197,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radar_5_clubs/u4.png"}},
{
          "id":"1ed8ed3a866f4af1b29b7bc619f8a769",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":115,
              "y":418},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c77f878aa14c85abf40c3aeba3eb8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":115,
                  "y":418},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/liste/u4.png"}},
{
          "id":"cfc9ff44819a4deebfad83f574b44fc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":418},
            "size":{
              "width":51,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9118d19e2c014c77844fc462763527d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":418},
                "size":{
                  "width":51,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Profil1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profil1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u8.png"}},
{
          "id":"732e5219bba74b85bfbd9c39b2b19772",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":418},
            "size":{
              "width":71,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef82a0e2c5b4314ab94dff7abbc44e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":418},
                "size":{
                  "width":71,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Radar 5 Clubs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"radar_5_clubs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/liste/u8.png"}},
{
          "id":"302efd6e940042ebb496f222f5074e46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":424},
            "size":{
              "width":30,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dfb79da76954f5190e8235430a40ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":424},
                "size":{
                  "width":30,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radar_5_clubs/u12.png"}},
{
          "id":"ba2573b2e06f4411b6fcb1439cf2e29d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":420},
            "size":{
              "width":27,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f9d5e6e047400b892b72fd3647b69f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":420},
                "size":{
                  "width":27,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Radar 5 Clubs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"radar_5_clubs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u14.png"}},
{
          "id":"3f3667a511c444c3a19871489e1d09d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":422},
            "size":{
              "width":26,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9b159a4fbb4590b5f504aef07595b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":422},
                "size":{
                  "width":26,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Profil1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profil1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u16.png"}},
{
          "id":"45db5ff11b4a4da79e6fc837fe331471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":130,
              "y":290},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9437871a6bbe4390a40e227d97811e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":130,
                  "y":290},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c22b3ba46b664a878fbe3db63b36d92a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":157},
            "size":{
              "width":17,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef36bc6852124c9c92439c8f623cb8fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":157},
                "size":{
                  "width":17,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Liste in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"liste.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/cluba/u16.png"}},
{
          "id":"182ad1ded93445d2aa7fc59372fb25bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":156,
              "y":154},
            "size":{
              "width":128,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5131c8a48444ddb0ee73a438cb0aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":156,
                  "y":154},
                "size":{
                  "width":128,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b96a3a2208b41a8bfb412a427960cc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":330},
            "size":{
              "width":45,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dee0e6ec54ef436295b496475444750c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":330},
                "size":{
                  "width":45,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa60ddba63374cf9859b3de469f23a1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":355},
            "size":{
              "width":38,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32699ca5428c4e4fa71dda5ead162e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":355},
                "size":{
                  "width":38,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6356c90d69b14ac5ada85157a324cd17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":200},
            "size":{
              "width":169,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443922c217004ab29d63b2c6b24ac4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":200},
                "size":{
                  "width":169,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/clubb/u24.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "13e1bc62a5864bc9bf2a10d73a7118f8":{
      "scriptId":"u0"},
    "808b515d389b4e1a8ba14be16174d556":{
      "scriptId":"u1"},
    "1ed8ed3a866f4af1b29b7bc619f8a769":{
      "scriptId":"u2"},
    "31c77f878aa14c85abf40c3aeba3eb8d":{
      "scriptId":"u3"},
    "cfc9ff44819a4deebfad83f574b44fc4":{
      "scriptId":"u4"},
    "9118d19e2c014c77844fc462763527d7":{
      "scriptId":"u5"},
    "732e5219bba74b85bfbd9c39b2b19772":{
      "scriptId":"u6"},
    "cef82a0e2c5b4314ab94dff7abbc44e5":{
      "scriptId":"u7"},
    "302efd6e940042ebb496f222f5074e46":{
      "scriptId":"u8"},
    "5dfb79da76954f5190e8235430a40ba2":{
      "scriptId":"u9"},
    "ba2573b2e06f4411b6fcb1439cf2e29d":{
      "scriptId":"u10"},
    "70f9d5e6e047400b892b72fd3647b69f":{
      "scriptId":"u11"},
    "3f3667a511c444c3a19871489e1d09d4":{
      "scriptId":"u12"},
    "8e9b159a4fbb4590b5f504aef07595b1":{
      "scriptId":"u13"},
    "45db5ff11b4a4da79e6fc837fe331471":{
      "scriptId":"u14"},
    "9437871a6bbe4390a40e227d97811e51":{
      "scriptId":"u15"},
    "c22b3ba46b664a878fbe3db63b36d92a":{
      "scriptId":"u16"},
    "ef36bc6852124c9c92439c8f623cb8fe":{
      "scriptId":"u17"},
    "182ad1ded93445d2aa7fc59372fb25bf":{
      "scriptId":"u18"},
    "bc5131c8a48444ddb0ee73a438cb0aad":{
      "scriptId":"u19"},
    "7b96a3a2208b41a8bfb412a427960cc8":{
      "scriptId":"u20"},
    "dee0e6ec54ef436295b496475444750c":{
      "scriptId":"u21"},
    "fa60ddba63374cf9859b3de469f23a1c":{
      "scriptId":"u22"},
    "32699ca5428c4e4fa71dda5ead162e77":{
      "scriptId":"u23"},
    "6356c90d69b14ac5ada85157a324cd17":{
      "scriptId":"u24"},
    "443922c217004ab29d63b2c6b24ac4ae":{
      "scriptId":"u25"}}});