$axure.loadCurrentPage({
  "url":"liste.html",
  "generationDate":new Date(1416701658387.46),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce80c17edd574fb496bbf82c5560eafb",
    "type":"Axure:Page",
    "name":"Liste",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"576ab08f817b47e68bc7f7ff7652a7b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":197,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8363865046594e92a2c430ce0ef8c0f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":197,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radar_5_clubs/u4.png"}},
{
          "id":"357330cb2d7a4b4b8436862df07c3b5b",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":160},
            "size":{
              "width":156,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ba7b4362b974b6aaaf56eb637e7d2bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":160},
                "size":{
                  "width":156,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/liste/u2.png"}},
{
          "id":"cd188a192bd44849a5825835d63a23e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":115,
              "y":418},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c053c1979c48ce8cc477d49fe9a9ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":115,
                  "y":418},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/liste/u4.png"}},
{
          "id":"37e55c939920484aa9bc34b2ab69b030",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":418},
            "size":{
              "width":51,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d328e6a41b84b92870dcbaa16084af9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":418},
                "size":{
                  "width":51,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Profil1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profil1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u8.png"}},
{
          "id":"b55b89741b2c4f8da198dea631aeff1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":418},
            "size":{
              "width":71,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"277c59498ced42b8970ca3a9ae7a0990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":418},
                "size":{
                  "width":71,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Radar 5 Clubs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"radar_5_clubs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/liste/u8.png"}},
{
          "id":"da96985e106b414c9dd2471318310229",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":424},
            "size":{
              "width":30,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad2065b2179e4d9380dffb28719ca686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":424},
                "size":{
                  "width":30,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/radar_5_clubs/u12.png"}},
{
          "id":"1c29bc9a683a4939b08744f0634ea21e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":420},
            "size":{
              "width":27,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"523244a5c7294c2db947a6ca9f650c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":420},
                "size":{
                  "width":27,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Radar 5 Clubs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"radar_5_clubs.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u14.png"}},
{
          "id":"e546e173a18e423cab256df4bc914188",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":422},
            "size":{
              "width":26,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd0cfecc7c83436990f42abe7f0fe6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":422},
                "size":{
                  "width":26,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Profil1 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"profil1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/radar_5_clubs/u16.png"}},
{
          "id":"ff4561360cbc454eadbea9df4745cafb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":157,
              "y":167},
            "size":{
              "width":128,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"764b1c4a13364a54afeaa0fea7c60599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":157,
                  "y":167},
                "size":{
                  "width":128,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e980b5630e04b3a9c92ca3b18f440c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":166},
            "size":{
              "width":18,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ab8abb977b45babfea0ab9fa8de8ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":166},
                "size":{
                  "width":18,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/liste/u18.png"}},
{
          "id":"5fc21d1de5e24b9fbb2be1218106c167",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":196},
            "size":{
              "width":156,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5dd5fc71f6941c39debf1dab10265be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":196},
                "size":{
                  "width":156,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubA in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cluba.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/liste/u20.png"}},
{
          "id":"fd817942e5c84f869bc90def46493b40",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":273},
            "size":{
              "width":156,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f163531dc3451598df9552a8c2ce54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":273},
                "size":{
                  "width":156,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubB in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubb.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/liste/u22.png"}},
{
          "id":"6bf9a19728c249d5bbe85f80047aefde",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":345},
            "size":{
              "width":156,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8030d1a9b3174858baf14402ad35e5bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":345},
                "size":{
                  "width":156,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubC in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubc.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/liste/u24.png"}},
{
          "id":"d35eb661a4be47f890c5a1290ee6c8cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":130,
              "y":216},
            "size":{
              "width":128,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e572becce38443d683e029f6582f6fb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":130,
                  "y":216},
                "size":{
                  "width":128,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubA in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"cluba.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4b85196ff854842b68c4fc04cd6d85f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":130,
              "y":290},
            "size":{
              "width":128,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb93c5e46bd44bbaa4cdaaf290ed01b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":130,
                  "y":290},
                "size":{
                  "width":128,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubB in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubb.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d7edcbae26847babb7895a6279185a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":130,
              "y":360},
            "size":{
              "width":128,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd36147fbb34f5b973316e50bee4c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":130,
                  "y":360},
                "size":{
                  "width":128,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open ClubC in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"clubc.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "576ab08f817b47e68bc7f7ff7652a7b3":{
      "scriptId":"u0"},
    "8363865046594e92a2c430ce0ef8c0f9":{
      "scriptId":"u1"},
    "357330cb2d7a4b4b8436862df07c3b5b":{
      "scriptId":"u2"},
    "4ba7b4362b974b6aaaf56eb637e7d2bd":{
      "scriptId":"u3"},
    "cd188a192bd44849a5825835d63a23e5":{
      "scriptId":"u4"},
    "62c053c1979c48ce8cc477d49fe9a9ed":{
      "scriptId":"u5"},
    "37e55c939920484aa9bc34b2ab69b030":{
      "scriptId":"u6"},
    "1d328e6a41b84b92870dcbaa16084af9":{
      "scriptId":"u7"},
    "b55b89741b2c4f8da198dea631aeff1a":{
      "scriptId":"u8"},
    "277c59498ced42b8970ca3a9ae7a0990":{
      "scriptId":"u9"},
    "da96985e106b414c9dd2471318310229":{
      "scriptId":"u10"},
    "ad2065b2179e4d9380dffb28719ca686":{
      "scriptId":"u11"},
    "1c29bc9a683a4939b08744f0634ea21e":{
      "scriptId":"u12"},
    "523244a5c7294c2db947a6ca9f650c9d":{
      "scriptId":"u13"},
    "e546e173a18e423cab256df4bc914188":{
      "scriptId":"u14"},
    "fd0cfecc7c83436990f42abe7f0fe6c1":{
      "scriptId":"u15"},
    "ff4561360cbc454eadbea9df4745cafb":{
      "scriptId":"u16"},
    "764b1c4a13364a54afeaa0fea7c60599":{
      "scriptId":"u17"},
    "5e980b5630e04b3a9c92ca3b18f440c4":{
      "scriptId":"u18"},
    "91ab8abb977b45babfea0ab9fa8de8ab":{
      "scriptId":"u19"},
    "5fc21d1de5e24b9fbb2be1218106c167":{
      "scriptId":"u20"},
    "b5dd5fc71f6941c39debf1dab10265be":{
      "scriptId":"u21"},
    "fd817942e5c84f869bc90def46493b40":{
      "scriptId":"u22"},
    "d0f163531dc3451598df9552a8c2ce54":{
      "scriptId":"u23"},
    "6bf9a19728c249d5bbe85f80047aefde":{
      "scriptId":"u24"},
    "8030d1a9b3174858baf14402ad35e5bf":{
      "scriptId":"u25"},
    "d35eb661a4be47f890c5a1290ee6c8cf":{
      "scriptId":"u26"},
    "e572becce38443d683e029f6582f6fb3":{
      "scriptId":"u27"},
    "c4b85196ff854842b68c4fc04cd6d85f":{
      "scriptId":"u28"},
    "cb93c5e46bd44bbaa4cdaaf290ed01b3":{
      "scriptId":"u29"},
    "4d7edcbae26847babb7895a6279185a3":{
      "scriptId":"u30"},
    "6cd36147fbb34f5b973316e50bee4c2d":{
      "scriptId":"u31"}}});